name: Wails build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'blunderDB'
            platform:  'linux/amd64'
          - name: 'blunderDB'
            platform:  'windows/amd64'


    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Setup and configure GoLang
      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: 1.23.1
      - run: go version
        shell: bash

      # Setup and configure NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: v23.4.0

      # install wails
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.9.2
        shell: bash

      - name: Install Linux Wails deps
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
        shell: bash

      - name: Build App
        run: wails build --platform ${{matrix.build.platform}} -webview2 download -o ${{matrix.build.name}} -upx -obfuscated -clean
        shell: bash
        
      - name: Add Linux perms
        run: chmod +x build/bin/*
        shell: bash

      # Upload build assets
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} ${{matrix.build.name}}
          path: |
            */bin/
            *\bin\*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*

