name: Wails build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'blunderDB'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'blunderDB'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'blunderDB'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Change directory
        run: cd blunderDB/src-go/blunderdb

      - name: List directory contents
        run: pwd && ls -la

      - name: Verify wails.json
        run: |
          if [ ! -f wails.json ]; then
            echo "wails.json not found!"
            exit 1
          fi

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        working-directory: ./src-go/blunderdb
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build: true
          nsis: false
          sign: false
          package: true
          build-platform: ${{ matrix.build.platform }}        
          wails-version: 'v2.9.2'
          wails-build-webview2: download
          go-version: '1.20'


